/**
 * PDF Export utility for chat responses
 * Uses html2pdf.js to convert formatted HTML content to PDF
 */

import html2pdf from 'html2pdf.js';
import { marked } from 'marked';
import { branding, AGENT } from './config';

// Agent URLs for the footer
const AGENT_URLS: Record<string, string> = {
  faa: 'https://faa.e-cfr.app',
  nrc: 'https://nrc.e-cfr.app',
  dod: 'https://dod.e-cfr.app',
};

export interface ExportOptions {
  question: string;
  response: string;
  citations?: string[];
  timestamp: Date;
}

/**
 * Format timestamp for filename (YYYYMMDD-HHmmss)
 */
function formatTimestampForFilename(date: Date): string {
  const pad = (n: number) => n.toString().padStart(2, '0');
  return `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}-${pad(date.getHours())}${pad(date.getMinutes())}${pad(date.getSeconds())}`;
}

/**
 * Format timestamp for display
 */
function formatTimestampForDisplay(date: Date): string {
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZoneName: 'short',
  });
}

/**
 * Build HTML content for PDF export (body content only with inline styles)
 */
function buildPdfHtml(options: ExportOptions): string {
  const { question, response, citations, timestamp } = options;
  const agentUrl = AGENT_URLS[AGENT] || AGENT_URLS.faa;
  
  // Render response markdown to HTML
  const responseHtml = marked.parse(response) as string;
  
  // Build citations section if present
  let citationsHtml = '';
  if (citations && citations.length > 0) {
    citationsHtml = `
      <div style="margin-top: 20px; padding-top: 16px; border-top: 1px solid #e0e0e0;">
        <h3 style="font-size: 10pt; color: #888; text-transform: uppercase; letter-spacing: 0.5px; margin: 0 0 8px 0;">References</h3>
        <p style="margin: 0;">${citations.join(', ')}</p>
      </div>
    `;
  }
  
  return `
    <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 11pt; line-height: 1.6; color: #1a1a2e; padding: 40px; max-width: 800px; box-sizing: border-box;">
      <div style="background: #f8f9fa; border-left: 4px solid ${branding.primaryColor}; padding: 16px; margin-bottom: 24px; border-radius: 4px;">
        <div style="font-size: 10pt; color: #666; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px;">Question</div>
        <div style="font-size: 12pt; font-weight: 500; color: #1a1a2e;">${escapeHtml(question)}</div>
      </div>
      
      <div style="margin-bottom: 24px;">
        <h2 style="font-size: 11pt; color: #666; text-transform: uppercase; letter-spacing: 0.5px; margin: 0 0 16px 0;">Response</h2>
        <div class="response-content">${responseHtml}</div>
      </div>
      
      ${citationsHtml}
      
      <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e0e0e0; text-align: center; color: #888; font-size: 10pt;">
        <div>Generated by <span style="font-weight: 600; color: ${branding.primaryColor};">${branding.name}</span></div>
        <div><a style="color: #666; text-decoration: none;" href="${agentUrl}">${agentUrl}</a></div>
        <div style="font-size: 9pt; margin-top: 8px;">${formatTimestampForDisplay(timestamp)}</div>
      </div>
    </div>
  `;
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

/**
 * Export a chat response to PDF
 */
export async function exportToPdf(options: ExportOptions): Promise<void> {
  const html = buildPdfHtml(options);
  
  const filename = `${AGENT}-agent-response-${formatTimestampForFilename(options.timestamp)}.pdf`;
  
  const pdfOptions = {
    margin: [10, 10, 10, 10],
    filename,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { 
      scale: 2,
      useCORS: true,
      logging: false,
    },
    jsPDF: { 
      unit: 'mm', 
      format: 'a4', 
      orientation: 'portrait' as const,
    },
    pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
  };
  
  // Pass HTML string directly to html2pdf
  await html2pdf().set(pdfOptions).from(html, 'string').save();
}
